import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import { ThemeProvider } from './context/themeContext'
import { AuthProvider } from './context/authContext' // Import AuthProvider
import { Toaster } from '@/components/ui/toaster'
import { ColorProvider } from './context/colorContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mood Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <ColorProvider>
              <Navbar />
              <main>{children}</main>
              <Toaster />
            </ColorProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
